name: CD

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
        
jobs:
  linux:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        runner: [ubuntu-22.04, ubuntu-24.04-arm]

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          submodules: recursive
 
      - name: Install Dependencies
        run: |
          sudo apt update -y
          sudo apt install -y libgl1-mesa-dev pkg-config cmake tar gzip curl git zip autoconf automake autoconf-archive libltdl-dev libibus-1.0-dev

      - name: Build
        run: |
            cmake -S . -B build \
            -DCMAKE_TOOLCHAIN_FILE=$PWD/vcpkg/scripts/buildsystems/vcpkg.cmake \
            -DCMAKE_C_COMPILER=/usr/bin/gcc
            -DCMAKE_CXX_COMPILER=/usr/bin/g++
            cmake --build build

      - name: Compress binaries
        run: |
          ls -lha build
          tar -czf triforce-${{ runner.os }}-${{ runner.arch }}.tar.gz -C build triforce

      - name: Create release
        if: success()
        uses: softprops/action-gh-release@v2
        with:
          files: triforce-${{ runner.os }}-${{ runner.arch }}.tar.gz

      - name: Upload release asset
        uses: actions/upload-artifact@v4
        with:
          name: triforce-${{ runner.os }}-${{ runner.arch }}
          path: triforce-${{ runner.os }}-${{ runner.arch }}.tar.gz

  macOS:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        runner: [macos-latest]

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          submodules: recursive
 
      - name: Install Dependencies
        run: |
          brew install cmake

      - name: Build
        run: |
          cmake -B build -DCMAKE_POLICY_VERSION_MINIMUM=3.5 -DCMAKE_TOOLCHAIN_FILE=$PWD/vcpkg/scripts/buildsystems/vcpkg.cmake
          cmake --build build

      - name: Compress binaries
        run: |
          ls -lha build
          tar -czf triforce-${{ runner.os }}-${{ runner.arch }}.tar.gz -C build triforce

      - name: Create release
        if: success()
        uses: softprops/action-gh-release@v2
        with:
          files: triforce-${{ runner.os }}-${{ runner.arch }}.tar.gz

      - name: Upload release asset
        uses: actions/upload-artifact@v4
        with:
          name: triforce-${{ runner.os }}-${{ runner.arch }}
          path: triforce-${{ runner.os }}-${{ runner.arch }}.tar.gz

  windows:
   runs-on: ${{ matrix.runner }}
   strategy:
     matrix:
       runner: [windows-latest]

   steps:
     - name: Check out code
       uses: actions/checkout@v4
       with:
         submodules: recursive

     - name: Install Dependencies
       shell: cmd
       run: |
        choco install -y cmake

     - name: Build with CMake
       shell: cmd
       run: |
        cmake -B build -DCMAKE_BUILD_TYPE=Debug -DCMAKE_POLICY_VERSION_MINIMUM='3.5' -DCMAKE_TOOLCHAIN_FILE=%CD%\vcpkg\scripts\buildsystems\vcpkg.cmake
        cmake --build build

     - name: Compress binaries (ZIP)
       run: |
         cd build\Debug
         7z a ..\..\triforce-${{ runner.os }}-${{ runner.arch }}.zip *

     - name: Create release
       if: success()
       uses: softprops/action-gh-release@v2
       with:
         files: triforce-${{ runner.os }}-${{ runner.arch }}.zip

     - name: Upload release asset
       uses: actions/upload-artifact@v4
       with:
         name: triforce-${{ runner.os }}-${{ runner.arch }}
         path: triforce-${{ runner.os }}-${{ runner.arch }}.zip